name: BullScheduler

services:
  bull-scheduler-redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'

  bull-scheduler:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - bull-scheduler-redis
    environment:
      REDIS_HOST: bull-scheduler-redis
      REDIS_PORT: 6379
      JOBS_WEBHOOK_URL: 'http://your-webhook-url.com'
      BULL_BOARD_USERNAME: admin
      BULL_BOARD_PASSWORD: admin
      SECRET_TOKEN: 'your-secret-token'
    env_file:
      - .env
