name: BullScheduler

services:
  bull-scheduler-redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'

  bull-scheduler:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - bull-scheduler-redis
    environment:
      REDIS_HOST: bull-scheduler-redis
      REDIS_PORT: 6379
      PORT: 3001
      JOBS_WEBHOOK_URL: 'http://your-webhook-url.com'
    env_file:
      - .env
